### ISSUE TITLE
Compute link budget and perform testing

### ISSUE THREAD

**Issue by surligas** [librespacefoundation/upsat-comms-software#37]

**Comment by manostheodoridis** [comment]
[W.I.P]

In the lab we should use the following rough estimation (i might have missed something), as a starting point, and move forward by adding attenuators in order to investigate the absolute RF margins.

For up-link at 145.835 MHz and assuming Ground Station we have:

Transmitter Power Output Pt (Watts): 20  (13dBW) 
Transmitter Antenna Gain Gt (dBi): 13
Transmitter Loss Lt (e.g matching losses in dB) : 0.5  
Frequency (MHz): 145.835
Distance (using ISS orbit properties and given an elevation angle of G.S antenna of  32,5 ° that leads us to a Slant Range around 700 km): 700 km
Miscellaneous Losses Lm (dB): 1
Receiver Loss Lr (e.g matching losses in dB): 0,5
Receiver Antenna Gr Gain (dBi): 2

We have Free Space Losses Lfs = 20log10(d in km) + 20log10(f in MHz) + 32,44=
=20×log (700)+20×log (145.835)+32.44= 132,62 dB

and Received Power = Pt  + Gt  -  Lt -  Lfs  -  Lm -  Lr  +  Gr  = 13+13−0.5−132.62−1−0.5+2=
= −106.62 dBW= -76,62 dBm.


Transmitter Power Output Pt (Watts): 0.1  (-10dBW= 20dBm) 
Transmitter Antenna Gain Gt (dBi): 0
Transmitter Loss Lt (e.g matching losses in dB) : 0 
Frequency (MHz): 145.835
Distance (using ISS orbit properties and given an elevation angle of G.S antenna of  32,5 ° that leads us to a Slant Range around 700 km): 700 km
Miscellaneous Losses Lm (dB): 0
Receiver Loss Lr (e.g matching losses in dB): 0
Receiver Antenna Gr Gain (dBi): 0

Our equation becomes :
Power Received in Upsat = Pt    -  Ltotal 
 
Since we want to simulate the Up-link in order to achieve Received Power of -76.62 dBm we must use attenuators of total value of : Ltotal = Pt - Power Received in Upsat ->
Ltotal = -10 + 106.62 = 96.62 dB of attenuators.

I will soon upload the Downlink rough estimations.
I am currently working on more precise calculations.

**Comment by manostheodoridis** [comment]
For Down-link at 435.8 MHz we have (on UPsat):

Transmitter Power Output Pt upsat (Watts): 1 (0 dBW = 30 dBm) 
Transmitter Antenna Gain Gt (dBi): 2
Transmitter Loss Lt (e.g matching losses in dB) : 0.5  
Frequency (MHz): 435.8
Distance (using ISS orbit properties and given an elevation angle of G.S antenna of  32,5 ° that leads us to a Slant Range around 700 km): 700 km
Miscellaneous Losses Lm (dB): 1
Receiver Loss Lr (e.g matching losses in dB): 0,5
Receiver Antenna Gr Gain (dBi): 13

We have Free Space Losses Lfs = 20log10(d in km) + 20log10(f in MHz) + 32,44=
=20×log (700)+20×log (435.8)+32.44= 142.13 dB

and Received Power in G.S = Pt  + Gt  -  Lt -  Lfs  -  Lm -  Lr  +  Gr  = 0+2-0.5-142.13-1-0.5+13=
= -129.13 dBW= -99.13 dBm.

In the lab our set up consists of:








Transmitter Power Output Pt (Watts): 1 (0 dBW = 30 dBm)
Transmitter Antenna Gain Gt (dBi): 0
Transmitter Loss Lt (e.g matching losses in dB) : 0 
Frequency (MHz): 435.8
Distance (using ISS orbit properties and given an elevation angle of G.S antenna of  32,5 ° that leads us to a Slant Range around 700 km): 700 km
Miscellaneous Losses Lm (dB): 0
Receiver Loss Lr (e.g matching losses in dB): 0
Receiver Antenna Gr Gain (dBi): 0

Our equation becomes :
Power Received in Upsat = Pt    -  Ltotal 
 
Since we want to simulate the Down-link in order to achieve Received Power of - 99.13 dBm  (-129.13 dBW) we must use attenuators of total value of : Ltotal 1= Pt - Power Received in G.S ->
Ltotal = -0 + 129.13 = 129.13 dB of attenuators.


*1. All the losses are accumulated in Ltotal.

**Comment by surligas** [comment]
Downlink works pretty well at 129 dB attenuation. 


![uploads/734e3a88-3145-42a9-8853-fb1e42005889/downlink_test.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F734e3a88-3145-42a9-8853-fb1e42005889%2Fdownlink_test.png)

**Comment by surligas** [comment]
Good news! Downlink also works at 130 dB attenuation. However, we have to narrow down the RX bandwidth of the SDR at 1 MHZ. This is quite easy in USRP B200 but not in hackRF or AirSPY.

**Comment by manostheodoridis** [comment]
If USRP provides 10dBm that is 10mW and indeed -20 dBW so the attenuation should be
Ltotal = -20 + 106.62= 86.62 dB of attenuators.

**Comment by surligas** [comment]
Uplink works at the specified attenuation values. I could reach attenuation up to 120 dB.
